apiVersion: v2
name: inventree
description: Helm chart for InvenTree - The Open Source Inventory and PLM Solution
keywords:
  - manufacturing
  - PLM
  - inventory management
home: https://inventree.org/
sources:
  - https://github.com/inventree/InvenTree/
icon: https://github.com/inventree/InvenTree/blob/master/assets/images/logo/inventree.svg
type: application

# Version info - CHANGEME
version: 0.3.4
appVersion: "1.1.11"

# Artifacthub annotations
artifacthub.io/license: MIT
artifacthub.io/links: |
  - name: Website
    url: https://inventree.org/
  - name: Documentation
    url: https://docs.inventree.org/en/stable/
